# Generated by Django 6.1 on 2026-08-21 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial_board', '0001_initial'),
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorialboardmember',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_members', to='journals.journal'),
        ),
    ]
