# Generated by Django 6.1 on 2026-08-21 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_journal_memberships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='editor_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reviewer_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='user',
            name='why_to_be',
        ),
    ]
