# Generated by Django 6.1 on 2026-08-21 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
        ('submissions', '0006_submission_doi_and_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='journalissue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='journalissue',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='journals.journal'),
        ),
        migrations.AddField(
            model_name='submission',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='journals.journal'),
        ),
        migrations.AddField(
            model_name='topicarea',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_areas', to='journals.journal'),
        ),
        migrations.AlterField(
            model_name='topicarea',
            name='slug',
            field=models.SlugField(),
        ),
    ]
