# Generated by Django 6.1 on 2026-08-21 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='journals/logos/')),
                ('accent_color', models.CharField(default='#2563eb', help_text='Hex color, e.g. #2563eb. Maps to --color-accent-blue.', max_length=7)),
                ('doi_prefix', models.CharField(default='10.5555', max_length=32)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('from_name', models.CharField(blank=True, help_text='Display name used as email sender / sign-off. Falls back to `name` if blank.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'journals_journal',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JournalMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('author', 'Author'), ('reviewer', 'Reviewer'), ('editor', 'Editor')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('why_to_be', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='journals.journal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journals_journal_membership',
                'constraints': [models.UniqueConstraint(fields=('user', 'journal', 'role'), name='uniq_membership_user_journal_role')],
            },
        ),
    ]
